# Generated by Django 4.2.4 on 2023-10-02 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0002_categorysubscriber_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, through='rest.CategorySubscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
